spring:
  application:
    name: nexus
  profiles:
    active: dev # Default profile
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8080}

# Common placeholders that profiles will fill
app:
  mail:
    from: ${MAIL_FROM:onboarding@resend.dev}